[tool.poetry]
name = "tidy3d"
version = "0.1.0"  # Thinking about bump2version
description = "A fast FDTD solver"
authors = ["Tyler Hughes <tyler@flexcompute.com>"]
license = "LGPLv2+"
readme = "README.md"
homepage = "https://github.com/flexcompute/tidy3d"
repository = "https://github.com/flexcompute/tidy3d"
classifiers = [
    "License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Operating System :: OS Independent",
]
documentation = "https://docs.flexcompute.com/projects/tidy3d/en/latest/"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/flexcompute/tidy3d/issues"

[tool.poetry.dependencies]
python = "^3.7"
pyroots = "^0.5.0"
xarray = "^0.16.2"
importlib-metadata = "^6.0.0"
h5netcdf = "1.0.2"
h5py = "^3.0.0"
rich = "<12.6.0"
matplotlib = "*"
shapely = "^2.0"
pydantic = "^2.0"
PyYAML = "*"
dask = "*"
toml = "*"
scipy = "*"
boto3 = "1.23.1"
requests = "*"
pyjwt = "*"
click = "8.0.3"
responses = "*"

[tool.poetry.dev-dependencies]
pre-commit = "*"
black = "22.3.0"
ruff = "*"
tox = "*"
pytest = "*"
pytest-timeout = "*"
memory_profiler = "*"
dill = "*"
ipython = "*"
gdspy = "*"
gdstk = "*"
trimesh = "3.20.0"
networkx = { version = ">=2.6.3, <=3.0" }
rtree = "1.0.1"

[tool.poetry.scripts]
tidy3d = "tidy3d.web.cli:tidy3d_cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
