[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "tidy3d"
version = "0.1.0"  # Replace with your actual version
description = "A fast FDTD solver"
authors = ["Tyler Hughes <tyler@flexcompute.com>"]
license = "GNU Lesser General Public License (LGPL) Version 2.1, February 1999"
readme = "README.md"
homepage = "https://github.com/flexcompute/tidy3d"
repository = "https://github.com/flexcompute/tidy3d"
classifiers = [
    "License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Operating System :: OS Independent",
]
documentation = ""  # Add if available

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/flexcompute/tidy3d/issues"

[tool.poetry.dependencies]
python = "^3.7"
pyroots = "^0.5.0"
xarray = "^0.16.2"
importlib-metadata = "^6.0.0"
h5netcdf = "1.0.2"
h5py = "^3.0.0"
rich = "<12.6.0"
matplotlib = "*"
shapely = "^2.0"
pydantic = "^2.0"
PyYAML = "*"
dask = "*"
toml = "*"
scipy = "*"
boto3 = "1.23.1"
requests = "*"
pyjwt = "*"
click = "8.0.3"
responses = "*"

[tool.poetry.dev-dependencies]
pre-commit = "*"
black = "22.3.0"
ruff = "*"
tox = "*"
pytest = "*"
pytest-timeout = "*"
memory_profiler = "*"
dill = "*"
ipython = "*"
gdspy = "*"
gdstk = "*"
trimesh = "3.20.0"
networkx = { version = ">=2.6.3, <=3.0" }
rtree = "1.0.1"

[tool.poetry.extras]
jax = [
    "jaxlib>=0.3.14,<=0.4.14; platform_system != 'Windows'",
    "jax[cpu]>=0.3.14,<=0.4.14; platform_system != 'Windows'",
    "jaxlib==0.3.14; platform_system == 'Windows' and python_version < '3.9'",
    "jax[cpu]==0.3.14; platform_system == 'Windows' and python_version < '3.9'",
    "jaxlib>=0.3.14,<=0.4.14; platform_system == 'Windows' and python_version >= '3.9'",
    "jax[cpu]>=0.3.14,<=0.4.14; platform_system == 'Windows' and python_version >= '3.9'"
]
gdspy = ["gdspy"]
gdstk = ["gdstk"]
trimesh = ["trimesh==3.20.0", "networkx >=2.6.3, <=3.0", "rtree==1.0.1"]
dev = ["pre-commit", "black==22.3.0", "ruff", "tox", "pytest", "pytest-timeout", "memory_profiler", "dill", "ipython", "gdspy", "gdstk", "trimesh"]


